AWSTemplateFormatVersion: '2010-09-09'
Description: 'Cloud Resume Challenge - Infrastructure managed by Terraform'

Metadata:
  Infrastructure:
    ManagedBy: Terraform
    StateBackend: S3
    StateLocation: vitraiaws-terraform-states/cloud-resume-challenge/terraform.tfstate

Parameters:
  DomainName:
    Type: String
    Default: vitraigabor.eu
    Description: Domain name for the website

Resources:
  # ==================== TERRAFORM STATE BUCKET ====================
  TerraformStateBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: vitraiaws-terraform-states

  # ==================== S3 WEBSITE BUCKET ====================
  WebsiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: vitraiaws-cloud-resume-challenge

  # ==================== CLOUDFRONT ====================
  CloudFrontOAC:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Name: cloud-resume-s3-oac
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4

  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        DefaultRootObject: index.html
        Aliases:
          - !Ref DomainName
        Origins:
          - DomainName: !GetAtt WebsiteBucket.RegionalDomainName
            Id: S3Origin
            S3OriginConfig:
              OriginAccessIdentity: ''
            OriginAccessControlId: !GetAtt CloudFrontOAC.Id
        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods:
            - GET
            - HEAD
          CachedMethods:
            - GET
            - HEAD
          CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6
        ViewerCertificate:
          AcmCertificateArn: !Ref ACMCertificate
          SslSupportMethod: sni-only
          MinimumProtocolVersion: TLSv1.2_2021

  # S3 Bucket Policy for CloudFront
  WebsiteBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref WebsiteBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: AllowCloudFrontServicePrincipal
            Effect: Allow
            Principal:
              Service: cloudfront.amazonaws.com
            Action: s3:GetObject
            Resource: !Sub '${WebsiteBucket.Arn}/*'
            Condition:
              StringEquals:
                'AWS:SourceArn': !Sub 'arn:aws:cloudfront::${AWS::AccountId}:distribution/${CloudFrontDistribution}'

  # ==================== ACM CERTIFICATE (us-east-1) ====================
  ACMCertificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Ref DomainName
      ValidationMethod: DNS
      DomainValidationOptions:
        - DomainName: !Ref DomainName
          HostedZoneId: !Ref HostedZone

  # ==================== ROUTE53 ====================
  HostedZone:
    Type: AWS::Route53::HostedZone
    Properties:
      Name: !Ref DomainName

  Route53RecordIPv4:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZone
      Name: !Ref DomainName
      Type: A
      AliasTarget:
        DNSName: !GetAtt CloudFrontDistribution.DomainName
        HostedZoneId: Z2FDTNDATAQYW2
        EvaluateTargetHealth: false

  Route53RecordIPv6:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZone
      Name: !Ref DomainName
      Type: AAAA
      AliasTarget:
        DNSName: !GetAtt CloudFrontDistribution.DomainName
        HostedZoneId: Z2FDTNDATAQYW2
        EvaluateTargetHealth: false

  # ==================== DYNAMODB ====================
  ViewCounterTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: cloud-resume-view-counter
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH

  # ==================== IAM ROLE ====================
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: cloud-resume-lambda-view-counter
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: lambda-dynamodb-access
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:GetItem
                  - dynamodb:UpdateItem
                Resource: !GetAtt ViewCounterTable.Arn

  # ==================== LAMBDA FUNCTION ====================
  ViewCounterFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: cloud-resume-view-counter
      Runtime: python3.12
      Handler: lambda_function.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Timeout: 10
      Code:
        ZipFile: |
          import json
          def lambda_handler(event, context):
              return {'statusCode': 200, 'body': json.dumps('Hello')}
      Environment:
        Variables:
          TABLE_NAME: !Ref ViewCounterTable
          ALLOWED_ORIGIN: !Sub 'https://${DomainName}'

  ViewCounterFunctionUrl:
    Type: AWS::Lambda::Url
    Properties:
      AuthType: NONE
      TargetFunctionArn: !GetAtt ViewCounterFunction.Arn
      Cors:
        AllowOrigins:
          - !Sub 'https://${DomainName}'
        AllowMethods:
          - GET
          - POST
        AllowHeaders:
          - '*'
        MaxAge: 86400

  ViewCounterFunctionUrlPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref ViewCounterFunction
      Action: lambda:InvokeFunctionUrl
      Principal: '*'
      FunctionUrlAuthType: NONE

  # ==================== CLOUDWATCH LOGS ====================
  LambdaLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/lambda/${ViewCounterFunction}'
      RetentionInDays: 7

Outputs:
  WebsiteBucketName:
    Description: S3 bucket name for website hosting (vitraiaws-cloud-resume-challenge)
    Value: !Ref WebsiteBucket

  TerraformStateBucketName:
    Description: S3 bucket storing Terraform state (vitraiaws-terraform-states)
    Value: !Ref TerraformStateBucket

  CloudFrontDistributionId:
    Description: CloudFront Distribution ID (cloud-resume-cloudfront)
    Value: !Ref CloudFrontDistribution

  CloudFrontDomainName:
    Description: CloudFront Distribution Domain Name
    Value: !GetAtt CloudFrontDistribution.DomainName

  WebsiteURL:
    Description: Website URL
    Value: !Sub 'https://${DomainName}'

  LambdaFunctionArn:
    Description: Lambda Function ARN (cloud-resume-view-counter)
    Value: !GetAtt ViewCounterFunction.Arn

  LambdaFunctionUrl:
    Description: Lambda Function URL
    Value: !GetAtt ViewCounterFunctionUrl.FunctionUrl

  DynamoDBTableName:
    Description: DynamoDB Table Name (cloud-resume-view-counter)
    Value: !Ref ViewCounterTable

  ACMCertificateArn:
    Description: ACM Certificate ARN (cloud-resume-certificate)
    Value: !Ref ACMCertificate

  HostedZoneId:
    Description: Route53 Hosted Zone ID (vitraigabor.eu)
    Value: !Ref HostedZone
